---
title: "Data Scraping with rvest"
author: "Math 271"
date: "Spring 22"
output:
  html_document:
    css: lab.css
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(rvest)
library(ggplot2)
library(lubridate)
```


```{r}
raw_html <- read_html("https://waterdata.usgs.gov/or/nwis/current/?type=dailydischarge&group_key=county_cd")

```


```{r}


url <- "https://waterdata.usgs.gov/or/nwis/current/?type=dailydischarge&group_key=county_cd"

# Read the HTML content of the webpage
webpage <- read_html(url)

# Use html_nodes to select the table based on HTML tags
table <- html_nodes(webpage, "table")

# Convert the table to a data frame
stream <- html_table(table)[[2]]
```

```{r}
cleaned_data <- stream %>% 
    rename("ID" = "StationNumber", "Name" = "Station name", flow_feb6 = "Dailymeanstream- flow (ft3/s)2/6", flow_feb7 = "Dailymeanstream- flow (ft3/s)2/7", "Difference" = "Change(ft3/s)") %>% 
  filter(!grepl("[a-zA-Z]", ID)) %>% 
  filter_all(all_vars(. != "--"))

cleaned_data$flow_feb6 <- as.numeric(cleaned_data$flow_feb6)

cleaned_data <- cleaned_data[!is.na(cleaned_data$flow_feb6), ]


cleaned_data$flow_feb7 <- as.numeric(cleaned_data$flow_feb7)

cleaned_data <- cleaned_data[!is.na(cleaned_data$flow_feb7), ]


cleaned_data$Difference <- as.numeric(cleaned_data$Difference)

cleaned_data <- cleaned_data[!is.na(cleaned_data$Difference), ]


log <- cleaned_data %>%
  mutate(log_sixth =log(flow_feb6, 10)) %>%
  mutate(log_seventh = log(flow_feb7, 10)) %>%
  mutate(dif = log(Difference, 10))

  
```

```{r}
ggplot(data = cleaned_data, aes(x = flow_feb6)) +
  geom_histogram(binwidth = 25, fill = "skyblue", color = "black") +
  labs(title = "Histogram of Flow Data", x = "Flow Feb6", y = "Frequency") 

ggplot(data = cleaned_data, aes(x = flow_feb7)) +
  geom_histogram(binwidth = 25, fill = "skyblue", color = "black") +
  labs(title = "Histogram of Flow Data", x = "Flow Feb6", y = "Frequency")


ggplot(data = cleaned_data, aes(x = Difference))+
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black") +
  labs(title = "Histogram of Flow Data", x = "Flow Feb6", y = "Frequency")





ggplot(data = log, aes(x = log_sixth)) +
  geom_histogram(binwidth = .25, fill = "skyblue", color = "black") +
  labs(title = "Histogram of Flow Data", x = "Flow Feb6", y = "Frequency")

ggplot(data = log, aes(x = log_seventh)) +
  geom_histogram(binwidth = .25, fill = "skyblue", color = "black") +
  labs(title = "Histogram of Flow Data", x = "Flow Feb6", y = "Frequency")


ggplot(data = log, aes(x = dif))+
  geom_histogram(binwidth = .25, fill = "skyblue", color = "black") +
  labs(title = "Histogram of Flow Data", x = "Flow Feb6", y = "Frequency")

```


```{r}

shapiro.test(log$flow_feb6)

shapiro.test(log$flow_feb7)

shapiro.test(log$log_sixth)

shapiro.test(log$log_seventh)


```


