---
title: "Data Scraping with rvest"
author: "Math 271"
date: "Spring 22"
output:
  html_document:
    css: lab.css
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(rvest)

library(lubridate)
```

```{r}
library(dplyr)
library(tidyverse)
```


```{r}
raw_html <- read_html("https://waterdata.usgs.gov/or/nwis/current/?type=dailydischarge&group_key=county_cd")

```



```{r}

url <- "https://waterdata.usgs.gov/or/nwis/current/?type=dailydischarge&group_key=county_cd"

# Read the HTML content of the webpage
webpage <- read_html(url)

# Use html_nodes to select the table based on HTML tags
table <- html_nodes(webpage, "table")

# Convert the table to a data frame
stream <- html_table(table)[[2]]
```

```{r}
cleaned_data <- stream %>% 
    rename("ID" = "StationNumber", "Name" = "Station name", "Stream Flow (ft³/s) (2/6)" = "Dailymeanstream- flow (ft3/s)2/6", "Stream Flow (ft³/s) (2/7)" = "Dailymeanstream- flow (ft3/s)2/7", "Difference" = "Change(ft3/s)") %>% 
  filter(!grepl("[a-zA-Z]", ID)) %>% 
  filter_all(all_vars(. != "--"))
  
```















